modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_display_url}"
authors="${mod_authors}"
description='''
Adds more ultimate skills to Tensura.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[mixins]]
config="${mod_id}.stextras.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="architectury"
    type="required"
    versionRange="[${architectury_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="manascore_storage"
    type="required"
    versionRange="[4.0.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="manascore_skill"
    type="required"
    versionRange="[4.0.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tensura"
    type="required"
    versionRange="[2.0.0.1,)"
    ordering="AFTER"
    side="BOTH"
